### ISSUE TITLE
Custom animation definition don't work on OUT

### ISSUE THREAD

**Issue by zhiga90** [radical-dreamers/animated-vue#4]
I copied your code from the main page.
Animation works on enter, but not on leave

`export default new GenericTransition('custom-fade-in-bounce-out', 'fadeIn', 'bounce', false)`

bounce animation dont' work

If reversed bounce and fadeIn, then fadeIn animation dont' work

**Comment by srodriki** [comment]
@zhiga90 

Thanks a lot for pointing this out. The example given in this repo's README had an error. The bounce animation is an "In" animation as defined in animate.css, thus it only works as an animation that plays well to show a component, but not when you try to hide it. 

I've already fixed that mistake so I hope it's clearer now. 

I believe it's also good to explain that such limitation comes from the way animate.css works, and not because of this plugin. Some animations are simply not meant for entrance, while others are not meant for exits. While many are self-explaining (have an "In" or "Out" suffix), others like "bounce" are kind of confusing until you try them out. 

Thanks a lot for giving this plugin a try and helping me make it better!

**Comment by srodriki** [comment]
Closed due to the user not responding anymore.
